src/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeDoneView
# from django.contrib.auth.views import PasswordChangeDoneView, PasswordChangeView,  PasswordResetCompleteView, \
#    PasswordResetConfirmView, PasswordResetDoneView, PasswordResetView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetView
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('accounts/', include('accounts.urls')),
    path('quiz/', include('quiz.urls')),
    path('accounts/change/', PasswordChangeView.as_view(), name='password_change'),
    path('accounts/change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/reset/', PasswordResetView.as_view(), name='password_reset'),
    path('accounts/reset/done', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/quiz/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import ExamDetailView, ExamListView, ExamResultCreateView, ExamResultDetailView, ExamResultQuestionView, \
    ExamResultUpdateView

app_name = 'quiz'

urlpatterns = [
    path('', ExamListView.as_view(), name='list'),
    path('<uuid:uuid>/', ExamDetailView.as_view(), name='details'),
    path('<uuid:uuid>/result/create/', ExamResultCreateView.as_view(), name='result_create'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/question/<int:order_num>/',
         ExamResultQuestionView.as_view(), name='question'),
    path('<uuid:uuid>/result/<uuid:res_uuid>/details/',
         TemplateView.as_view(template_name='results/details.html'), name='result_details'),
]

src/templates/exams/details.html
{% extends 'base.html' %}


{% block title %}
    Details of exam
{% endblock %}

{% block header %}
    Exam: {{ exam.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <table class="table table-striped">
                    <tbody>
                        <tr>
                            <td>Description</td>
                            <td>{{ exam.description }}</td>
                        </tr>
                        <tr>
                            <td>Count of questions</td>
                            <td>{{ exam.questions.count }}</td>
                        </tr>
                        <tr>
                            <td>Count of runs</td>
                            <td>{{ exam.results.count }}</td>
                        </tr>
                        <tr>
                            <td>The best result</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>The best user</td>
                            <td>N/A</td>
                        </tr>
                        <tr>
                            <td>Last run</td>
                            <td>N/A</td>
                        </tr>
                    </tbody>
              </table>
            </div>
        </div>
        <div class="row">
            <form method="post"
                  class="d-flex justify-content-center mt-5 mb-2"
                  action="{% url 'quiz:result_create' exam.uuid %}">
                {% csrf_token %}
                <input class="btn btn-outline-success m-3" type="submit" value="START">
                <a class="btn btn-outline-primary m-3" href="{% url 'quiz:list' %}">Back to list</a>
            </form>
        </div>
    </div>
{% endblock %}

src/templates/exams/list.html
{% extends 'base.html' %}

{% block title %}
    Exam list
{% endblock %}

{% block header %}
    Exam list.
{% endblock %}

{% block content %}
    {% if exams %}
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Description</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for exam in exams %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ exam.title }}</td>
                    <td>{{ exam.description }}</td>
                    <td><a href="{% url 'quiz:details' uuid=exam.uuid %}">Details</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>There are no tests yet!</p>
    {% endif %}
{% endblock %}

src/templates/exams/question.html
{% extends 'base.html' %}

{% block title %}
    Question {{ question.order_num }}
{% endblock %}

{% block header %}
    {{ question.text }}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ choices.management_form }}
            {% for form in choices %}
                <div class="mt-1">
                    {{ form.is_selected }} <label for="{{ form.is_selected.id_for_label }}">
                        {{ form.text.value }}
                    </label>
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-success mt-5">Дальше ></button>
        </form>
    </div>
{% endblock %}